In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import RepeatedKFold
from joblib import dump, load
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
grid_search_mlp = load('XGB_3Class.joblib') 

C:\Users\nakul\anaconda3\envs\env_capstone\Lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 1.2.1 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [3]:
test = pd.read_excel('Test Set 20.xlsx')
test.head()

pdb  Hbond  Hphob  consurf    asa  Electron-ion interaction potential  \
0  1a4y      1      0        6  0.360                              0.0959   
1  1a4y      2      0        5  0.994                              0.0242   
2  1a4y      3      0        7  0.173                              0.0761   
3  1a4y      1      0        3  0.501                              0.0959   
4  1a4y      4      0        8  0.690                              0.0959   

   Hydrophobicity  Number of electrostatic charge  \
0           -1.76                               1   
1           -0.40                               0   
2           -0.69                               0   
3           -1.76                               1   
4           -1.76                               1   

   Number of potential hydrogen bonds  Hydrophilicity  Propensity  \
0                                   4            -0.5        0.27   
1                                   4            -0.5        0.41   
2                                   4             0.2       -0.11   
3                                   4            -0.5        0.27   
4                                   4            -0.5        0.27   

   Isoelectric points  2-class  3-class  
0               5.405        1        2  
1               5.565        0        0  
2               5.650        0        0  
3               5.405        0        0  
4               5.405        0        0

In [4]:
X_test = test.iloc[:, 1:12]

In [5]:
y_test  = test['3-class']

In [6]:
y_pred =grid_search_mlp.predict(X_test)

In [7]:
cm1 = confusion_matrix(y_test,y_pred)
cm1

array([[80,  2, 12],
       [13,  0,  7],
       [23,  2, 23]], dtype=int64)

In [8]:
precision = np.diagonal(cm1)/np.sum(cm1, axis = 0)
sen_recall = np.diagonal(cm1)/np.sum(cm1, axis = 1)
acc = accuracy_score(y_test,y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
#mcc = matthews_corrcoef(y_test, y_pred)
#auc = roc_auc_score(y_test, y_pred, average='weighted')
#specificity =  cm1[1,1]/(cm1[0,1]+cm1[1,1])
print((sen_recall))
print((precision))

[0.85106383 0.         0.47916667]
[0.68965517 0.         0.54761905]


In [9]:
#print(precision)

#print(sen_recall)

#print(acc)

print(f1)

#print(mcc)

#print(auc)

#print(specificity)


0.5935332157554379


In [10]:
firstclass = (2*(sen_recall[0]
*precision[0]))/((sen_recall[0]
+precision[0]))
firstclass

0.761904761904762

In [11]:
secclass = (2*(sen_recall[1]
*precision[1]))/((sen_recall[1]
+precision[1]))
secclass

C:\temp\ipykernel_2252\4219704323.py:1: RuntimeWarning: invalid value encountered in scalar divide
  secclass = (2*(sen_recall[1]


nan

In [12]:
thirdclass = (2*(sen_recall[2]
*precision[2]))/((sen_recall[2]
+precision[2]))
thirdclass

0.5111111111111111

In [13]:
supportc1 = cm1[0][0] + cm1[1][0] + cm1[2][0]
sp1 = supportc1/162

In [14]:
supportc2 = cm1[0][1] + cm1[1][1] + cm1[2][1]
sp2 = supportc2/162

In [15]:
supportc3 = cm1[0][2] + cm1[1][2] + cm1[2][2]
sp3 = supportc3/162

In [16]:
f1weighted = (firstclass*sp1) + (secclass*sp2) + (thirdclass*sp3)
f1weighted

nan